name = "verify-rsa-jwt-cloudflare-worker"
compatibility_date = "2023-05-18"

[vars]
JWKS_URI = "https://christojeffrey.kinde.com/.well-known/jwks"
VERIFY_RSA_JWT="JWK_CACHE"

[[kv_namespaces]]
binding = "JWK_CACHE"
id = "e909b11fee604b1bb2e93953189c26a5"